name: aravt
description: "A Flutter project for the game Aravt."
publish_to: 'none'
version: 1.0.0+1

environment:
 sdk: '>=3.2.3 < 4.0.0'

dependencies:
 flutter:
   sdk: flutter
 provider: ^6.1.2  
 google_fonts: ^6.2.1
 path_provider: ^2.0.0
 uuid: ^4.4.0
 cupertino_icons: ^1.0.6
 window_manager: ^0.5.1

dev_dependencies:
 flutter_test:
   sdk: flutter
 flutter_lints: ^3.0.0

flutter:
 uses-material-design: true

 assets:
   - assets/images/
   - assets/images/items/
   - assets/images/sprites/
   - assets/backgrounds/
   - assets/tiles/
